### ISSUE TITLE
no prom_pred.py  script in repo?

### ISSUE THREAD

**Issue by rLannes** [zhuyaner/Depicter#2]
Hi,
 I wanted to use Depicter on custom data. 
following the README, I should launch Depicter using prom_pred.py, but it is absent from the repo.
Trying to use Depicter_pred.py.
I got the following error
` Please check the format of your predicting data! `
Which when I raise the exception instead of printing, I got the following error message:
```
Traceback (most recent call last):
  File "../../../Software/depicter_env_dir/Depicter/Depicter_pred.py", line 438, in <module>
    main()
  File "../../../Software/depicter_env_dir/Depicter/Depicter_pred.py", line 404, in main
    from capsulenet_Com import Capsnet_main
ModuleNotFoundError: No module named 'capsulenet_Com'
```

And there is no capsulenet_Com module/file in the repos.
Is this the right repo for using Depicter on my own data?

**Comment by jcarocont** [comment]
hello. I also want to use my own data for training the model but there 0 explanation how to do it. u could get to know how to do it??
